# Form implementation generated from reading ui file 'ChatForm.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(616, 426)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.TextEdit = TextEdit(parent=Frame)
        self.TextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.TextEdit.setReadOnly(True)
        self.TextEdit.setObjectName("TextEdit")
        self.gridLayout.addWidget(self.TextEdit, 0, 0, 1, 2)
        self.CommandBar = CommandBar(parent=Frame)
        self.CommandBar.setMaximumSize(QtCore.QSize(16777215, 34))
        self.CommandBar.setObjectName("CommandBar")
        self.gridLayout.addWidget(self.CommandBar, 1, 0, 1, 2)
        self.TextEdit_2 = TextEdit(parent=Frame)
        self.TextEdit_2.setMaximumSize(QtCore.QSize(16777215, 51))
        self.TextEdit_2.setObjectName("TextEdit_2")
        self.gridLayout.addWidget(self.TextEdit_2, 2, 0, 1, 1)
        self.PushButton = PushButton(parent=Frame)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 2, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.TextEdit.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Microsoft YaHei\',\'PingFang SC\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px;\">AI: 有什么可以帮您的吗？😎 </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.PushButton.setText(_translate("Frame", "发送"))
from qfluentwidgets import CommandBar, PushButton, TextEdit
