# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(554, 508)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.StrongBodyLabel_2 = StrongBodyLabel(parent=Frame)
        self.StrongBodyLabel_2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.gridLayout.addWidget(self.StrongBodyLabel_2, 6, 0, 1, 1)
        self.StrongBodyLabel_3 = StrongBodyLabel(parent=Frame)
        self.StrongBodyLabel_3.setMaximumSize(QtCore.QSize(16777215, 24))
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.gridLayout.addWidget(self.StrongBodyLabel_3, 9, 0, 1, 1)
        self.TextEdit_2 = TextEdit(parent=Frame)
        self.TextEdit_2.setMaximumSize(QtCore.QSize(16777215, 41))
        self.TextEdit_2.setObjectName("TextEdit_2")
        self.gridLayout.addWidget(self.TextEdit_2, 4, 0, 1, 3)
        self.EditableComboBox = EditableComboBox(parent=Frame)
        self.EditableComboBox.setObjectName("EditableComboBox")
        self.gridLayout.addWidget(self.EditableComboBox, 13, 0, 1, 3)
        self.TextEdit = TextEdit(parent=Frame)
        self.TextEdit.setMaximumSize(QtCore.QSize(16777215, 41))
        self.TextEdit.setObjectName("TextEdit")
        self.gridLayout.addWidget(self.TextEdit, 3, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 15, 0, 1, 1)
        self.StrongBodyLabel = StrongBodyLabel(parent=Frame)
        self.StrongBodyLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout.addWidget(self.StrongBodyLabel, 2, 0, 1, 1)
        self.StrongBodyLabel_4 = StrongBodyLabel(parent=Frame)
        self.StrongBodyLabel_4.setMaximumSize(QtCore.QSize(16777215, 24))
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.gridLayout.addWidget(self.StrongBodyLabel_4, 12, 0, 1, 1)
        self.TitleLabel = TitleLabel(parent=Frame)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.HyperlinkButton = HyperlinkButton(parent=Frame)
        self.HyperlinkButton.setObjectName("HyperlinkButton")
        self.gridLayout.addWidget(self.HyperlinkButton, 15, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 8, 0, 1, 1)
        self.LineEdit = LineEdit(parent=Frame)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout.addWidget(self.LineEdit, 7, 0, 1, 3)
        self.LineEdit_2 = LineEdit(parent=Frame)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout.addWidget(self.LineEdit_2, 10, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 1)
        self.PushButton = PushButton(parent=Frame)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 15, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 14, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem5, 11, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.StrongBodyLabel_2.setText(_translate("Frame", "AI Temperature -AI随机性"))
        self.StrongBodyLabel_3.setText(_translate("Frame", "AI History Message-软件保存的历史信息数量"))
        self.EditableComboBox.setText(_translate("Frame", "gpt-3.5-turbo"))
        self.StrongBodyLabel.setText(_translate("Frame", "OpenAI Setting"))
        self.StrongBodyLabel_4.setText(_translate("Frame", "AI Model"))
        self.TitleLabel.setText(_translate("Frame", "设置"))
        self.HyperlinkButton.setText(_translate("Frame", "重新加载配置"))
        self.PushButton.setText(_translate("Frame", "保存"))
from qfluentwidgets import EditableComboBox, HyperlinkButton, LineEdit, PushButton, StrongBodyLabel, TextEdit, TitleLabel
