# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShortVideoDownload.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(608, 505)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.StrongBodyLabel = StrongBodyLabel(Frame)
        self.StrongBodyLabel.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.StrongBodyLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.StrongBodyLabel.setWordWrap(True)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout.addWidget(self.StrongBodyLabel, 2, 0, 1, 2)
        self.PlainTextEdit = PlainTextEdit(Frame)
        self.PlainTextEdit.setMaximumSize(QtCore.QSize(16777215, 41))
        self.PlainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.PlainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.PlainTextEdit.setUndoRedoEnabled(True)
        self.PlainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.PlainTextEdit.setObjectName("PlainTextEdit")
        self.gridLayout.addWidget(self.PlainTextEdit, 3, 0, 1, 1)
        self.PushButton = PushButton(Frame)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 3, 1, 1, 1)
        self.TextEdit = TextEdit(Frame)
        self.TextEdit.setObjectName("TextEdit")
        self.gridLayout.addWidget(self.TextEdit, 4, 0, 2, 1)
        self.PushButton_2 = PushButton(Frame)
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout.addWidget(self.PushButton_2, 4, 1, 2, 1)
        self.DisplayLabel = DisplayLabel(Frame)
        self.DisplayLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.gridLayout.addWidget(self.DisplayLabel, 0, 0, 1, 2)
        self.TitleLabel = TitleLabel(Frame)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 1, 0, 1, 2)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.StrongBodyLabel.setText(_translate("Frame", "支持皮皮虾/抖音/微视/快手/6间房/哔哩哔哩/微博/绿洲/度小视/开眼/陌陌/皮皮搞笑/全民k歌/逗拍/虎牙/新片场/哔哩哔哩/Acfun/美拍/西瓜视频/火山小视频/网易云Mlog/好看视频/QQ小世界"))
        self.PushButton.setText(_translate("Frame", "解析"))
        self.PushButton_2.setText(_translate("Frame", "下载"))
        self.DisplayLabel.setText(_translate("Frame", "短视频解析"))
        self.TitleLabel.setText(_translate("Frame", "By Canf"))
from qfluentwidgets import DisplayLabel, PlainTextEdit, PushButton, StrongBodyLabel, TextEdit, TitleLabel
