# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(625, 619)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.StrongBodyLabel = StrongBodyLabel(Frame)
        self.StrongBodyLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout.addWidget(self.StrongBodyLabel, 1, 0, 1, 2)
        self.CaptionLabel_3 = CaptionLabel(Frame)
        self.CaptionLabel_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CaptionLabel_3.setObjectName("CaptionLabel_3")
        self.gridLayout.addWidget(self.CaptionLabel_3, 3, 0, 1, 1)
        self.TitleLabel = TitleLabel(Frame)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 2)
        self.CaptionLabel_4 = CaptionLabel(Frame)
        self.CaptionLabel_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CaptionLabel_4.setObjectName("CaptionLabel_4")
        self.gridLayout.addWidget(self.CaptionLabel_4, 3, 1, 1, 1)
        self.CaptionLabel_2 = CaptionLabel(Frame)
        self.CaptionLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.gridLayout.addWidget(self.CaptionLabel_2, 2, 1, 1, 1)
        self.CaptionLabel = CaptionLabel(Frame)
        self.CaptionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.gridLayout.addWidget(self.CaptionLabel, 2, 0, 1, 1)
        self.CaptionLabel_5 = CaptionLabel(Frame)
        self.CaptionLabel_5.setObjectName("CaptionLabel_5")
        self.gridLayout.addWidget(self.CaptionLabel_5, 4, 1, 1, 1)
        self.CommandBar = CommandBar(Frame)
        self.CommandBar.setObjectName("CommandBar")
        self.gridLayout.addWidget(self.CommandBar, 4, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.StrongBodyLabel.setText(_translate("Frame", "<Yiyan>"))
        self.CaptionLabel_3.setText(_translate("Frame", "PM："))
        self.TitleLabel.setText(_translate("Frame", "<City>"))
        self.CaptionLabel_4.setText(_translate("Frame", "weather："))
        self.CaptionLabel_2.setText(_translate("Frame", "风向 N/A"))
        self.CaptionLabel.setText(_translate("Frame", "温度：N/A"))
        self.CaptionLabel_5.setText(_translate("Frame", "Caption label"))
from qfluentwidgets import CaptionLabel, CommandBar, StrongBodyLabel, TitleLabel
